version: "3.9"

x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: techsy

services:
  db:
    image: postgres:15-alpine
    environment: *db-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/techsy?schema=public
    command: >
      sh -c "npx prisma migrate deploy &&
            node dist/index.js"
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
